---
site_name: Systemli Ticker Widget
site_author: Systemli
repo_url: https://github.com/systemli/ticker-widget

nav:
  - Home: index.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: "blue"
    accent: "blue"

extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://www.systemli.org
    - icon: fontawesome/brands/github
      link: https://github.com/systemli

markdown_extensions:
  - admonition
