/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TickerTimeline {
        "apiUrl": string;
        "domain": string;
        "header": string;
        "limit": number;
    }
}
declare global {
    interface HTMLTickerTimelineElement extends Components.TickerTimeline, HTMLStencilElement {
    }
    var HTMLTickerTimelineElement: {
        prototype: HTMLTickerTimelineElement;
        new (): HTMLTickerTimelineElement;
    };
    interface HTMLElementTagNameMap {
        "ticker-timeline": HTMLTickerTimelineElement;
    }
}
declare namespace LocalJSX {
    interface TickerTimeline {
        "apiUrl"?: string;
        "domain"?: string;
        "header"?: string;
        "limit"?: number;
    }
    interface IntrinsicElements {
        "ticker-timeline": TickerTimeline;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ticker-timeline": LocalJSX.TickerTimeline & JSXBase.HTMLAttributes<HTMLTickerTimelineElement>;
        }
    }
}
