/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TickerTimeline {
        /**
          * @default ''
         */
        "header": string;
        /**
          * @default 10
         */
        "limit": number;
        "origin": string;
    }
}
declare global {
    interface HTMLTickerTimelineElement extends Components.TickerTimeline, HTMLStencilElement {
    }
    var HTMLTickerTimelineElement: {
        prototype: HTMLTickerTimelineElement;
        new (): HTMLTickerTimelineElement;
    };
    interface HTMLElementTagNameMap {
        "ticker-timeline": HTMLTickerTimelineElement;
    }
}
declare namespace LocalJSX {
    interface TickerTimeline {
        /**
          * @default ''
         */
        "header"?: string;
        /**
          * @default 10
         */
        "limit"?: number;
        "origin"?: string;
    }

    interface TickerTimelineAttributes {
        "header": string;
        "origin": string;
        "limit": number;
    }

    interface IntrinsicElements {
        "ticker-timeline": Omit<TickerTimeline, keyof TickerTimelineAttributes> & { [K in keyof TickerTimeline & keyof TickerTimelineAttributes]?: TickerTimeline[K] } & { [K in keyof TickerTimeline & keyof TickerTimelineAttributes as `attr:${K}`]?: TickerTimelineAttributes[K] } & { [K in keyof TickerTimeline & keyof TickerTimelineAttributes as `prop:${K}`]?: TickerTimeline[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ticker-timeline": LocalJSX.IntrinsicElements["ticker-timeline"] & JSXBase.HTMLAttributes<HTMLTickerTimelineElement>;
        }
    }
}
